/**
 * Pre-build guard.
 *
 * simulationAdapter.js and mapVisuals.js import two JSON files that are
 * GENERATED by the Python engine, not hand-written:
 *
 *   src/data/trace.json           <- engine/run_simulation.py
 *   src/data/bhopal_basemap.json  <- engine/build_graph.py
 *
 * Vercel builds from git and has no Python runtime, so both files must be
 * committed. If they are missing, Vite fails with an opaque "failed to
 * resolve import" that gives no hint about the actual cause. This turns that
 * into an instruction.
 */

import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "src", "data");

const REQUIRED = [
  { file: "trace.json", producer: "engine/run_simulation.py", key: "scenarios" },
  { file: "bhopal_basemap.json", producer: "engine/build_graph.py", key: "roads" }
];

const problems = [];

for (const { file, producer, key } of REQUIRED) {
  const path = join(dataDir, file);
  if (!existsSync(path)) {
    problems.push(`  MISSING  src/data/${file}\n           regenerate with: python ${producer}`);
    continue;
  }
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8"));
    if (!(key in parsed)) {
      problems.push(`  INVALID  src/data/${file} has no "${key}" key\n           regenerate with: python ${producer}`);
    }
  } catch {
    problems.push(`  CORRUPT  src/data/${file} is not valid JSON\n           regenerate with: python ${producer}`);
  }
}

if (problems.length > 0) {
  console.error("\nBuild blocked - generated engine data is missing or unusable:\n");
  console.error(problems.join("\n"));
  console.error(
    "\nThese files are produced by the Python engine and must be committed to git,\n" +
    "because the deploy build has no Python runtime. From the repo root:\n\n" +
    "  cd engine && python build_graph.py && python run_simulation.py\n" +
    "  git add frontend/src/data/trace.json frontend/src/data/bhopal_basemap.json\n"
  );
  process.exit(1);
}
