/**
 * Pre-build guard.
 *
 * mapVisuals.js imports one JSON file that is GENERATED by the Python
 * engine, not hand-written:
 *
 *   src/data/bhopal_basemap.json  <- backend/build_graph.py
 *
 * This is the static visual basemap only (roads/zones geometry for the
 * canvas). Everything else — orders, routes, results, metrics — comes from
 * a LIVE call to the local API server (see src/data/apiClient.js) and is
 * never baked into a build-time file. If bhopal_basemap.json is missing,
 * Vite fails with an opaque "failed to resolve import" that gives no hint
 * about the actual cause; this turns that into an instruction.
 *
 * This app is meant to run locally via `python3 run_app.py` (see
 * README.md), not deployed to a static host — the backend requires an
 * actual Python process.
 */

import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const dataDir = join(here, "..", "src", "data");

const REQUIRED = [
  { file: "bhopal_basemap.json", producer: "backend/build_graph.py", key: "roads" }
];

const problems = [];

for (const { file, producer, key } of REQUIRED) {
  const path = join(dataDir, file);
  if (!existsSync(path)) {
    problems.push(`  MISSING  src/data/${file}\n           regenerate with: cd backend && python build_graph.py`);
    continue;
  }
  try {
    const parsed = JSON.parse(readFileSync(path, "utf8"));
    if (!(key in parsed)) {
      problems.push(`  INVALID  src/data/${file} has no "${key}" key\n           regenerate with: cd backend && python build_graph.py`);
    }
  } catch {
    problems.push(`  CORRUPT  src/data/${file} is not valid JSON\n           regenerate with: cd backend && python build_graph.py`);
  }
}

if (problems.length > 0) {
  console.error("\nBuild blocked - generated basemap data is missing or unusable:\n");
  console.error(problems.join("\n"));
  console.error(
    "\nThis file is produced by the Python engine's map builder. From the repo root:\n\n" +
    "  cd backend && python build_graph.py\n"
  );
  process.exit(1);
}
